[package]
name = "tui-popup"
authors = ["Joshka"]
version = "0.2.3"
description = "A simple popup for ratatui"
license = "MIT"
repository = "https://github.com/joshka/tui-popup"
documentation = "https://docs.rs/tui-popup"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-getters = "0.3.0"
derive_setters = "0.1.6"
ratatui = "0.26.1"

[dev-dependencies]
color-eyre = "0.6.2"
crossterm = "0.27.0"
lipsum = "0.9.0"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"
expect_used = "warn"
