[package]
name = "tui-popup"
authors = ["Joshka"]
version = "0.3.1"
description = "A simple popup for ratatui"
license = "MIT"
repository = "https://github.com/joshka/tui-popup"
documentation = "https://docs.rs/tui-popup"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-getters = "0.4.0"
derive_setters = "0.1.6"
ratatui = { version = "0.26.3", features = ["unstable-widget-ref"] }

[dev-dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
lipsum = "0.9.1"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
